### ISSUE TITLE
Design database schema and tables

### ISSUE THREAD

**Issue by robstrader** [Code-the-Dream-School/hh-team8-back#1]

**Comment by sam-lee-ku** [comment]
Websites that help you to diagram db tables and schemas:
[_lucidchart_](https://www.lucidchart.com/pages/landing?utm_source=google&utm_medium=cpc&utm_campaign=_chart_en_us_mixed_rlsa_brand_exact&km_CPC_CampaignId=20744746494&km_CPC_AdGroupID=163925669228&km_CPC_Keyword=lucidcharts&km_CPC_MatchType=e&km_CPC_ExtensionID=&km_CPC_Network=g&km_CPC_AdPosition=&km_CPC_Creative=679878152768&km_CPC_TargetID=aud-2227034459243:kwd-84176206937&km_CPC_Country=1017537&km_CPC_Device=c&km_CPC_placement=&km_CPC_target=&gad_source=1&gclid=CjwKCAiAl4a6BhBqEiwAqvrquvewspJNYEd1ORuxSc3pcHVWdAH5cZxv1C3cgvOG22JXLYtj7ATUNBoCMg0QAvD_BwE)

[_dbdiagram_](https://dbdiagram.io/d)

**Comment by olgaosadchuk** [comment]
https://dbdiagram.io/d/6747374be9daa85acae8e720
