### ISSUE TITLE
Configure the Database Connection

### ISSUE THREAD

**Issue by sam-lee-ku** [Code-the-Dream-School/hh-team8-back#2]
Create a .env file in your root project. 

- This will be used to store sensitive database credentials

The content of the file will look something like this:
`DB_HOST=localhost
DB_PORT=5432
DB_NAME=your_database_name
DB_USER=your_user_name
DB_PASSWORD=your_password`

**Comment by olgaosadchuk** [comment]
done

**Comment by olgaosadchuk** [comment]
done
